### ISSUE TITLE
No module named captcha.image

### ISSUE THREAD

**Issue by xjtuwxg** [BruceDone/tensorflow-demos#1]
I tried crack_captcha on RHEL7.3. After I have installed "python-recaptcha-client.noarch", "perl-GD-SecurityImage.noarch", "php-pear-Text-CAPTCHA.noarch" and "perl-Authen-Captcha.noarch", it still got an error:

[root@localhost crack_captcha]# python src/gen_model.py 
Traceback (most recent call last):
  File "src/gen_model.py", line 4, in <module>
    from gen_image import text_to_array
  File "/root/tensorflow-demos-master/crack_captcha/src/gen_image.py", line 3, in <module>
    from captcha.image import ImageCaptcha
ImportError: No module named captcha.image

**Comment by BruceDone** [comment]
Hi @xjtuwxg , did you ever try this one ? 

https://github.com/lepture/captcha
